Feature/141 conversation reconnect after 24 hours
akvo/rag-doll pull request #142
Opened 2024-11-29 03:30 UTC by wayangalihpratama

2024-12-09 14:05 UTC, jcbashdown requested changes
Looks good! Mostly there I think. Just highlighted a couple of things I find unclear and asked a couple of questions.

2024-12-09 14:05 UTC, jcbashdown commented on backend/core/socketio_config.py
> +            await twilio_client.whatsapp_message_template_create(
It looks like it sends the reconnect template to the farmer but shouldn't it also take `clean_message_body` as a `content_variable` in that case?

2024-12-11 03:00 UTC, wayangalihpratama commented on backend/db/crud_chat.py
> +            # only chat from client/farmer will be calculated
Hi @jcbashdown , 
Yes, the client refer to the Farmer in our application.

2024-12-11 03:42 UTC, wayangalihpratama commented on backend/core/socketio_config.py
> +            await twilio_client.whatsapp_message_template_create(
Yes correct,
I will fix that.

2024-12-12 14:44 UTC, jcbashdown approved these changes

2024-12-13 00:35 UTC, wayangalihpratama commented on backend/core/socketio_config.py
>          send_conversation_reconnect_template = check_24h_window(
Resolved

2024-12-13 03:04 UTC, merged