Feature/25 setup socketio
akvo/rag-doll pull request #26
Opened 2024-06-26 10:17 UTC by wayangalihpratama

- #25

2024-06-29 04:30 UTC, dedenbangkit requested changes
The faker seeder seems invalid on seeding fake phone number @wayangalihpratama

2024-07-01 05:41 UTC, wayangalihpratama commented
> The faker seeder seems invalid on seeding fake phone number @wayangalihpratama

- I solved the socketio testing problem by using AsyncMock on test case.

2024-07-01 12:03 UTC, kjkoster requested changes

2024-07-01 12:03 UTC, kjkoster commented on packages/Akvo_rabbitmq_client/src/Akvo_rabbitmq_client/queue_message_util.py
> +                "message_id": str(uuid4()),
The message ID should not be generated server-side, as stated in https://docs.google.com/document/d/12koOL2T5Wstga0EBEwicDZgKq_Y9-dVpOP0OKin5xL8/edit#heading=h.u16r6w9czmp3 I think this is important for deduplication.

2024-07-01 12:03 UTC, kjkoster commented on packages/Akvo_rabbitmq_client/tests/test_queue_message_util.py
> +class TestQueueMessageUtil(unittest.TestCase):
Good to see tests!

2024-07-02 06:48 UTC, wayangalihpratama commented on backend/core/socketio_config.py
> +            "phone": "+628123456789",
Hi @kjkoster , 
This phone number will be fetch from user/client, so in my opinion we doesn't need to  move this into `.env`

2024-07-02 06:52 UTC, wayangalihpratama commented on backend/core/socketio_config.py
> +    await sio_server.emit('chats', msg)
For this, Socket.IO will send the message back to the frontend. I am still working on it, so we don't need to send the message back from the frontend socket. I tried removing the code on line 42, but the chats did not appear in the frontend.

2024-07-02 06:53 UTC, wayangalihpratama commented on frontend/src/components/chats/ChatWindow.js
> +    return chats.map((c, ci) => {
for now we are not using the ordering yet.

2024-07-02 06:54 UTC, wayangalihpratama commented on packages/Akvo_rabbitmq_client/src/Akvo_rabbitmq_client/queue_message_util.py
> +                "user_id": user_id
Sorry, I don't get you, 
I'm thinking to change the client_id and user_id into phone_number

2024-07-02 07:09 UTC, wayangalihpratama commented on backend/core/socketio_config.py
> +    await sio_server.emit('chats', msg)
- we can use `indexedDB` in FE to store the chats locally.
- generate UUID in the FE if the message started from user/extension officer, else we will use MessageSid from twilio/slack.

2024-07-02 07:11 UTC, wayangalihpratama commented on frontend/src/components/chats/ChatWindow.js
> +    return chats.map((c, ci) => {
- use UTC time

2024-07-02 09:22 UTC, kjkoster commented on frontend/src/components/chats/ChatWindow.js
> +    return chats.map((c, ci) => {
See my updated description of the frontend component: https://docs.google.com/document/d/12koOL2T5Wstga0EBEwicDZgKq_Y9-dVpOP0OKin5xL8/edit#heading=h.ecgg5gdax48i

2024-07-02 13:11 UTC, wayangalihpratama commented
Hi @kjkoster , 
I have tried to implement the queue message format on both the frontend and backend. However, some values are still static and will be updated later once we connect all the elements (Slack, Twilio, etc.).

2024-07-03 07:11 UTC, kjkoster approved these changes

2024-07-03 07:37 UTC, merged