Feature/29 merge slackbot fn to backend
akvo/rag-doll pull request #30
Opened 2024-07-04 08:46 UTC by wayangalihpratama

### TODO / DONE

---

2024-07-07 15:10 UTC, kjkoster requested changes
Hi Galih, this PR seems to be a mix of good changes and ones that feel a tad unfinished to me Can you please tell me what your intention is? Do you propose to merge this into master or did you expect me to do an intermediate review?

2024-07-09 13:32 UTC, dedenbangkit commented on backend/clients/twilio_client.py
> +                phone = conversation_envelope.get("user_phone_number")
Yes, please write comment / notes @wayangalihpratama.

You can also shorten the code to:
```python
phone = conversation.get("client_phone_number", conversation.get("user_phone_number"))
```

2024-07-09 13:32 UTC, dedenbangkit commented on backend/clients/twilio_client.py
> +            iso_timestamp = datetime.now().isoformat()
```python
datetime.now(timezone.utc).isoformat()
```

2024-07-09 23:34 UTC, wayangalihpratama commented on backend/clients/twilio_client.py
> +                conversation_id="__CHANGEME__",
When we receive a message from Twilio, we will format the message into queue format then put that message into queue. The incoming message will have `MessageSid` as our message_id in queue, and should we set and use `uuid` as a conversation_id here?

2024-07-10 06:40 UTC, dedenbangkit commented on backend/routes/user_routes.py
> +async def send_to_twilio(phone_number: int, login_token: str):
https://github.com/akvo/rag-doll/pull/30/commits/6a40d5c3fa479ff38a64e92ada2bd9ff590bfaf6

2024-07-11 01:57 UTC, wayangalihpratama commented on frontend/src/components/chats/ChatWindow.js
> +        client_phone_number: "_CHANGEME_", // change to your phone number to test
When should be the conversation ID defined?

2024-07-12 03:29 UTC, dedenbangkit approved these changes

2024-07-12 08:06 UTC, kjkoster requested changes

2024-07-12 08:06 UTC, kjkoster commented on backend/routes/slack_routes.py
> +RABBITMQ_QUEUE_SLACKBOT_REPLIES = os.getenv("RABBITMQ_QUEUE_SLACKBOT_REPLIES")
This can go.

2024-07-12 08:06 UTC, kjkoster commented on frontend/src/components/chats/ChatWindow.js
> +      if (c?.conversation_envelope?.sender_role === "user") {
Please make that an enum.

2024-07-12 09:15 UTC, wayangalihpratama commented
I will remove the conversation ID in the new PR related to HTTP session.

2024-07-12 09:26 UTC, kjkoster commented on backend/tests/conftest.py
> +    async def producer(self, body, routing_key, reply_to):
Is `reply_to` needed?

2024-07-12 09:34 UTC, kjkoster approved these changes

2024-07-12 09:41 UTC, merged