Fix deployment by removing the requirement to install `slackbot`, sin…
akvo/rag-doll pull request #38
Opened 2024-07-13 12:55 UTC by kjkoster

…ce that was merged into the backend. Documentation updates.

2024-07-15 01:26 UTC, anjarakvo requested changes

2024-07-15 01:26 UTC, anjarakvo commented on docker-compose-rag-doll-only.yml
To make the API work, it seems you also need to add the backend service to this docker-compose file.

2024-07-15 06:50 UTC, kjkoster commented on docker-compose-rag-doll-only.yml
Will do.

2024-07-15 07:26 UTC, kjkoster commented
@anjarakvo Keep in mind that this change means that your deployed `.env` needs to change quite a bit. You can also remove the firewall ports that you opened for the Slack and Twilio bots. These no longer exist, so the ports may be closed.

@dedenbangkit I notice there is a `/dev` at the end of the database URL. Is that proper for Kubernetes also, or should that be a different URL?

2024-07-15 07:34 UTC, dedenbangkit commented
> @anjarakvo Keep in mind that this change means that your deployed `.env` needs to change quite a bit. You can also remove the firewall ports that you opened for the Slack and Twilio bots. These no longer exist, so the ports may be closed.
> 
> @dedenbangkit I notice there is a `/dev` at the end of the database URL. Is that proper for Kubernetes also, or should that be a different URL?

@anjarakvo stored the values of all the environment variables somewhere else (usually in secret repository). Anything related to the Docker Compose values will be overridden by the .yaml file that he has. There is no need to worry about the environment values in Docker Compose. Since this is a different standard deployment, I don't know where Anjar stores the template.yml file. CMIIW @anjarakvo

2024-07-15 07:42 UTC, kjkoster commented
> @anjarakvo stored the values of all the environment variables somewhere else (usually in secret repository). Anything related to the Docker Compose values will be overridden by the .yaml file that he has. There is no need to worry about the environment values in Docker Compose. Since this is a different standard deployment, I don't know where Anjar stores the template.yml file. CMIIW @anjarakvo

In that case, should we not remove the environment variables from the Compose file? No point in having them if they get ignored.

2024-07-16 06:12 UTC, dedenbangkit commented
> > @anjarakvo stored the values of all the environment variables somewhere else (usually in secret repository). Anything related to the Docker Compose values will be overridden by the .yaml file that he has. There is no need to worry about the environment values in Docker Compose. Since this is a different standard deployment, I don't know where Anjar stores the template.yml file. CMIIW @anjarakvo
> 
> In that case, should we not remove the environment variables from the Compose file? No point in having them if they get ignored.

But it will be required for the CI pipeline if there's any test. Although we use environment variables in Docker Compose, the environment will not be available after the Docker image is built.

2024-07-16 07:36 UTC, dedenbangkit approved these changes

2024-07-16 09:49 UTC, anjarakvo approved these changes

2024-07-16 09:50 UTC, merged